---
title: "CFA and Pilot Replication Analyses"
output: 
    html_document:
      code_download: TRUE
      toc: TRUE
      toc_float:
        collapsed: FALSE
      toc_depth: 1
      code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r data prep, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# Loading packages
library(psych)
library(effects)
library(magrittr) # part of the tidyverse but must be read in on its own
library(parameters)
library(dplyr)
library(tidyr)
library(rio)
library(ggplot2)
library(emmeans)

# Functions to clean document, get data from wide to long format
source("functions/Cleaning.R")

# Setting global chunk options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

options(scipen = 999)

# Importing data
wide_data <- import("data/diss_main_combined_data_basic_clean.csv")

# Cleaning data using functions
long_data <- get_wrangled(wide_data)

clean_data <- remove_participants(long_data)
```

# Correlation matrix for CFA

```{r}
cfa_vars <- clean_data %>% 
  select(sub_id, distance_coffee, distance_town, realistic_q, 
         symbolic_q, explicit_targ, explicit_group) %>% 
  unique() %>% 
  na.omit() %>% 
  select(distance_coffee, distance_town, realistic_q, 
         symbolic_q, explicit_targ, explicit_group)

cor_matrix_cfa <- cor(cfa_vars)
cor_matrix_cfa

cor_plot_cfa <- corrplot(cor_matrix_cfa, method = "number")

colnames(cor_plot_cfa) = rep(c('Distance: Coffee', 
                                       'Distance: Town',
                                       'Realistic',
                                       'Symbolic',
                                       'Explicit: Target',
                                       'Explicit: Group'))

rownames(cor_plot_cfa) = rep(c('Distance: Coffee', 
                                       'Distance: Town',
                                       'Realistic',
                                       'Symbolic',
                                       'Explicit: Target',
                                       'Explicit: Group'))
corrplot(cor_plot_cfa, 
         is.corr = TRUE, 
         #method = "number", 
         method = 'color',
         col.lim = c(0, 1),
         tl.cex = .85,
         tl.col = 'black',
         addgrid.col = 'white',
         addCoef.col = 'grey50')

```

*This corresponds to factorability, an assumption of Factor Analysis*