---
title: "Other Pre-Registered Analyses"
output: 
    html_document:
      code_download: TRUE
      toc: TRUE
      toc_float:
        collapsed: FALSE
      toc_depth: 1
      code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r data prep, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# Loading packages
library(psych)
library(lme4)
library(nlme)
library(sjPlot)
library(effects)
library(magrittr) # part of the tidyverse but must be read in on its own
library(parameters)
library(dplyr)
library(tidyr)
library(rio)
library(ggplot2)
library(emmeans)
library(corrplot)

# Functions to clean document, get data from wide to long format
source("functions/Cleaning.R")

# Setting global chunk options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

options(scipen = 999)

# Importing data
wide_data <- import("data/diss_main_combined_data_basic_clean.csv")

# Cleaning data using functions
long_data <- get_wrangled(wide_data)

clean_vars <- get_vars_cleaned(long_data)

clean_data <- remove_participants(clean_vars)

clean_data %<>%    
  mutate(itt_comp = rowMeans(select(., c("realistic_q", "symbolic_q"))),
         itt_comp_gmc = scale(itt_comp, center = T, scale = F))
```

# Model 1b: Added threat condition

*Technically not pre-registered or predicted, but consistent with other predictions about threat*

## BFI

### MLM Results


## ELI

### MLM Results

### Random Slopes/No random Intercept

```{r}
mod_1_data_eli <- clean_data %>% 
  select(sub_id, eli_number, eli_targ_pmc, eli_self_pmc, itt_comp_gmc,
         target_condition, eli_targ, eli_self) %>% 
  unique() %>% 
  na.omit() 

model1b_eli_randslopes <- lmer(eli_targ_pmc ~ eli_self_pmc*itt_comp_gmc
                               *target_condition + 
                     (0 + eli_self_pmc | sub_id), 
                   data = mod_1_data_eli) # Model only works with the whole data-set (clean_data), not when filtered down to only include observations (thus none repeated) for this analysis with mod_1_data_bfi

tab_model(model1b_eli_randslopes,
          digits = 3)
```

Similiar to the BFI, but no interaction.

#### Simple Slopes

##### Target condition main effect

```{r}
mod1b_simpslopes_eli_me <- emtrends(model1b_eli_randslopes, ~ target_condition,
                              var ="eli_self_pmc",
                              at = list(target_condition = c("CONTROL", 
                                                             "LOSS", 
                                                             "WARM")))

mod1b_simpslopes_bfi_me
```

#### Visualization

```{r}
mod1b_eli <- effect("eli_self_pmc:target_condition",
                         xlevels = list(target_condition = c("CONTROL",
                                                             "WARM",
                                                             "LOSS")),
                         mod = model1b_eli_randslopes)

mod1b_eli <- as.data.frame(mod1b_eli)
mod1b_eli$target_condition <- as.factor(mod1b_eli$target_condition)

ggplot(mod1b_eli, aes(eli_self_pmc, fit, group = target_condition)) +
  geom_smooth(method = "lm", 
                size = .7, 
                se = FALSE,
                colour = "black", 
                aes(linetype = target_condition)) +
    theme_minimal(base_size = 13) +
    theme(legend.key.size = unit(1, "cm")) +
  scale_linetype_manual("Target condition",
                        breaks = c("CONTROL", "WARM", "LOSS"), 
                       labels = c("Control",
                                  "Warm",
                                  "Loss"),
                       values = c("solid",
                                  "dashed",
                                  "dotted")) +
    labs(title = "Projection by target condition",
         subtitle = "Using the ELI; Accounting for threat composite",
       x = "ELI responses for self",
       y = "ELI responses for target")
```
