---
title: "Slopes for mediation paths"
output: 
    html_document:
      code_download: TRUE
      toc: TRUE
      toc_float:
        collapsed: FALSE
      toc_depth: 1
      code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r data prep, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# Loading packages
library(psych)
library(lme4)
library(nlme)
library(sjPlot)
library(effects)
library(magrittr) # part of the tidyverse but must be read in on its own
library(parameters)
library(dplyr)
library(tidyr)
library(rio)
library(ggplot2)
library(emmeans)
library(corrplot)

# Functions to clean document, get data from wide to long format
source("functions/Cleaning.R")

# Setting global chunk options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

options(scipen = 999)

# Importing data
wide_data <- import("data/diss_main_combined_data_basic_clean.csv")

# Cleaning data using functions
long_data_bfi <- get_wrangled_bfi(wide_data)
long_data_eli <- get_wrangled_eli(wide_data)

clean_vars_bfi <- get_vars_cleaned(long_data_bfi)
clean_vars_eli <- get_vars_cleaned(long_data_eli)

clean_data_bfi <- remove_participants(clean_vars_bfi)
clean_data_eli <- remove_participants(clean_vars_eli)

clean_data_bfi %<>%    
  mutate(itt_comp = rowMeans(select(., c("realistic_q", "symbolic_q"))),
         itt_comp_gmc = scale(itt_comp, center = T, scale = F))

clean_data_eli %<>%    
  mutate(itt_comp = rowMeans(select(., c("realistic_q", "symbolic_q"))),
         itt_comp_gmc = scale(itt_comp, center = T, scale = F))
```

# Projection {.tabset .tabset-fade .tabset-pills}

## Only composite

Corresponds to path b in the mediation (effect of threat composite on projection)

```{r}
data_bfi <- clean_data_bfi %>% 
  select(sub_id, bfi_number, bfi_targ_pmc, bfi_self_pmc, itt_comp_gmc,
         target_condition, bfi_targ, bfi_self, bfi_stereo, bfi_stereo_pmc) %>% 
  unique() %>% 
  na.omit() 

bfi_nostereo_comp <- lmer(bfi_targ_pmc ~ bfi_self_pmc*itt_comp_gmc +
                     (bfi_self_pmc | sub_id), data = data_bfi)
summary(bfi_nostereo_comp)
tab_model(bfi_nostereo_comp)
```


### Simple Slopes

```{r}
threat_levels = list(itt_comp_gmc = c(-1.07, 0.0, 1.07))
simpslopes_bfi_nostereo2 <- emtrends(bfi_nostereo_comp, ~ itt_comp_gmc,
                              var ="bfi_self_pmc",
                              at = c(threat_levels))


simpslopes_bfi_nostereo2
test(simpslopes_bfi_nostereo2)
pairs(simpslopes_bfi_nostereo2)
```

### Visualization

```{r}
bfi_nostereo_comp_df <- effect("bfi_self_pmc:itt_comp_gmc",
                         xlevels = list(itt_comp_gmc = c(-1.07, 0.0, 1.07)),
                         mod = bfi_nostereo_comp)

bfi_nostereo_comp_df <- as.data.frame(bfi_nostereo_comp_df)
bfi_nostereo_comp_df$itt_comp_gmc <- as.factor(bfi_nostereo_comp_df$itt_comp_gmc)

ggplot(bfi_nostereo_comp_df, aes(bfi_self_pmc, fit, group = itt_comp_gmc)) +
  geom_smooth(method = "lm", 
                size = .7, 
                se = FALSE,
                colour = "black", 
                aes(linetype = itt_comp_gmc)) +
    theme_minimal(base_size = 13) +
    theme(legend.key.size = unit(1, "cm")) +
  scale_linetype_manual("Target-level threat",
                        breaks = c("-1.07", "0", "1.07"), 
                       labels = c("Low",
                                  "Average",
                                  "High"),
                       values = c("solid",
                                  "dashed",
                                  "dotted")) +
    labs(title = "Projection by target-level threat",
         subtitle = "Using the BFI",
       x = "BFI responses for self",
       y = "BFI responses for target")
```

### Assumptions

```{r}
# checking normality of conditional residuals
qqnorm(residuals(bfi_nostereo_comp), main="Q-Q plot for conditional residuals")

# checking the normality of the random effects (here random intercept):
qqnorm(ranef(bfi_nostereo_comp)$sub_id$bfi_self_pmc,
       main="Q-Q plot for the self random effect")

# Checking residuals for intercept
qqnorm(ranef(bfi_nostereo_comp)$sub_id$`(Intercept)`,
       main="Q-Q plot for the random intercept")

plot_model(bfi_nostereo_comp, type='diag')
```


## Only target variable

```{r}
bfi_nostereo_targ <- lmer(bfi_targ_pmc ~ bfi_self_pmc*target_condition +
                     (bfi_self_pmc | sub_id), data = data_bfi)
summary(bfi_nostereo_targ)
tab_model(bfi_nostereo_targ)
```

### Simple Slopes

```{r}
targ_levels <-list(target_condition = c("CONTROL", "LOSS", "WARM"))
simpslopes_bfi_nostereo_targ <- emtrends(bfi_nostereo_targ, ~ target_condition,
                              var ="bfi_self_pmc",
                              at = targ_levels)


simpslopes_bfi_nostereo_targ
test(simpslopes_bfi_nostereo_targ)
pairs(simpslopes_bfi_nostereo_targ)
```

### Visualization

```{r}
bfi_nostereo_targ_df <- effect("bfi_self_pmc:target_condition",
                         xlevels = list(target_condition = c("CONTROL",
                                                             "WARM",
                                                             "LOSS")),
                         mod = bfi_nostereo_targ)

bfi_nostereo_targ_df <- as.data.frame(bfi_nostereo_targ_df)
bfi_nostereo_targ_df$target_condition <- as.factor(bfi_nostereo_targ_df$target_condition)

bfi_nostereo_targ_df %<>% 
  mutate(target_condition = forcats::fct_relevel(target_condition, c("CONTROL", "WARM", "LOSS")))

ggplot(bfi_nostereo_targ_df, aes(bfi_self_pmc, fit, group = target_condition)) +
  geom_smooth(method = "lm", 
                size = .7, 
                se = TRUE,
                colour = "black", 
                aes(linetype = target_condition)) +
    theme_minimal(base_size = 13) +
    theme(legend.key.size = unit(1, "cm")) +
  scale_linetype_manual("Target Variable",
                        breaks = c("CONTROL", "WARM", "LOSS"), 
                       labels = c("Least threatening",
                                  "Medium threatening",
                                  "Most threatening"),
                       values = c("solid",
                                  "dashed",
                                  "dotted")) +
    labs(x = "BFI responses for self",
       y = "BFI responses for target")
```

### Assumptions

```{r}
# checking normality of conditional residuals
qqnorm(residuals(bfi_nostereo_targ), main="Q-Q plot for conditional residuals")

# checking the normality of the random effects (here random intercept):
qqnorm(ranef(bfi_nostereo_targ)$sub_id$bfi_self_pmc,
       main="Q-Q plot for the self random effect")

# Checking residuals for intercept
qqnorm(ranef(bfi_nostereo_targ)$sub_id$`(Intercept)`,
       main="Q-Q plot for the random intercept")

plot_model(bfi_nostereo_targ, type='diag')
```