---
title: "Supplemental Analyses"
output: 
    html_document:
      code_download: TRUE
      toc: TRUE
      toc_float:
        collapsed: FALSE
      toc_depth: 1
      code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r data prep, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
# Loading packages
library(psych)
library(effects)
library(magrittr) # part of the tidyverse but must be read in on its own
library(parameters)
library(dplyr)
library(tidyr)
library(rio)
library(ggplot2)
library(emmeans)
library(lavaan)

# Functions to clean document, get data from wide to long format
source("functions/Cleaning.R")

# Setting global chunk options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

options(scipen = 999)

# Importing data
wide_data <- import("data/diss_main_combined_data_basic_clean.csv")

# Cleaning data using functions
long_data <- get_wrangled(wide_data)

clean_data <- remove_participants(long_data)
```

# Exploring relationship of ELI vars with politics {.tabset .tabset-fade .tabset-pills}

```{r}
eli_wide <- clean_data %>% 
  select(sub_id, eli_number, eli_self, pol_orient_1, pol_orient_2, pol_orient_3) %>% 
  unique() %>% 
  pivot_wider(names_from = eli_number, values_from = eli_self) %>% 
  select(-sub_id)

eli_pol_cor <- cor(eli_wide)

eli_pol_cor_plot <- corrplot(eli_pol_cor, method = "number")

colnames(eli_pol_cor_plot) = rep(c('Politics: Overall',
                                       'Politics: Social',
                                       'Politics: Economic',
                                       'ELI 1',
                                       'ELI 2',
                                       'ELI 3',
                                       'ELI 4',
                                       'ELI 5',
                                       'ELI 6',
                                       'ELI 7',
                                       'ELI 8',
                                       'ELI 9',
                                       'ELI 10'))

rownames(eli_pol_cor_plot) = rep(c('Politics: Overall',
                                       'Politics: Social',
                                       'Politics: Economic',
                                       'ELI 1',
                                       'ELI 2',
                                       'ELI 3',
                                       'ELI 4',
                                       'ELI 5',
                                       'ELI 6',
                                       'ELI 7',
                                       'ELI 8',
                                       'ELI 9',
                                       'ELI 10'))
corrplot(eli_pol_cor_plot, 
         is.corr = TRUE, 
         #method = "number", 
         method = 'color',
         col.lim = c(0, 1),
         tl.cex = .85,
         tl.col = 'black',
         addgrid.col = 'white',
         addCoef.col = 'grey50')
```

Responses on the ELI are not related to responses on the political orientation questions.

Replicate analyses from Pilot using other measures in this doc
